### PR TITLE
Development

### PR DESCRIPTION
**Pull request by ericgriffis**
- Status Page differentiates between [staging](https://newyorkuniversitydivisionoflibrariesstaging.statuspage.io/) and [production](https://nyulibraries.statuspage.io/)
- Emails differentiate between staging ("staging outage") and production ("major/partial/degraded")
- Emails recognize "services now operational" after staging outage

### CODE REVIEW

**Comment by ericgriffis** [comment]
@barnabyalter @hab278 let me know your thoughts

**Comment by barnabyalter** [comment]
@ericgriffis `StagingApplication < Application` might be simpler as its own subclass. That would DRY up that class.

**Comment by barnabyalter** [comment]
👍

**Comment by barnabyalter** [comment]
@ericgriffis looks good to me. go ahead and merge when you're ready

**Pull request merged**
